In [1]:
import os
import pandas as pd

In [7]:
path = "D:\CD\IFSC_CODE"
files = os.listdir(path)
files

['IFCB2009_01.xls',
 'IFCB2009_02.xls',
 'IFCB2009_03.xls',
 'IFCB2009_04.xls',
 'IFCB2009_05.xls',
 'IFCB2009_06.xls',
 'IFCB2009_07.xls',
 'IFCB2009_08.xls',
 'IFCB2009_09.xls',
 'IFCB2009_10.xls',
 'IFCB2009_100.xls',
 'IFCB2009_101.xls',
 'IFCB2009_102.xls',
 'IFCB2009_104.xls',
 'IFCB2009_105.xls',
 'IFCB2009_106.xls',
 'IFCB2009_107.xls',
 'IFCB2009_108.xls',
 'IFCB2009_109.xls',
 'IFCB2009_11.xls',
 'IFCB2009_111.xls',
 'IFCB2009_112.xls',
 'IFCB2009_113.xls',
 'IFCB2009_114.xls',
 'IFCB2009_116.xls',
 'IFCB2009_117.xls',
 'IFCB2009_118.xls',
 'IFCB2009_119.xls',
 'IFCB2009_12.xls',
 'IFCB2009_120.xls',
 'IFCB2009_121.xls',
 'IFCB2009_122.xls',
 'IFCB2009_123.xls',
 'IFCB2009_124.xls',
 'IFCB2009_125.xls',
 'IFCB2009_126.xls',
 'IFCB2009_127.xls',
 'IFCB2009_128.xls',
 'IFCB2009_129.xls',
 'IFCB2009_13.xls',
 'IFCB2009_130.xls',
 'IFCB2009_131.xls',
 'IFCB2009_132.xls',
 'IFCB2009_133.xls',
 'IFCB2009_135.xls',
 'IFCB2009_136.xls',
 'IFCB2009_137.xls',
 'IFCB2009_138.xls',
 'IFCB2009_139.xls',
 'IFCB2009_14.xls',
 'IFCB2009_140.xls',
 'IFCB2009_141.xls',
 'IFCB2009_142.xls',
 'IFCB2009_143.xls',
 'IFCB2009_144.xls',
 'IFCB2009_145.xls',
 'IFCB2009_146.xls',
 'IFCB2009_147.xls',
 'IFCB2009_148.xls',
 'IFCB2009_149.xls',
 'IFCB2009_15.xls',
 'IFCB2009_150.xls',
 'IFCB2009_151.xls',
 'IFCB2009_152.xls',
 'IFCB2009_153.xls',
 'IFCB2009_154.xls',
 'IFCB2009_155.xls',
 'IFCB2009_156.xls',
 'IFCB2009_157.xls',
 'IFCB2009_158.xls',
 'IFCB2009_159.xls',
 'IFCB2009_16.xls',
 'IFCB2009_160.xls',
 'IFCB2009_161.xls',
 'IFCB2009_162.xls',
 'IFCB2009_163.xls',
 'IFCB2009_164.xls',
 'IFCB2009_165.xls',
 'IFCB2009_166.xls',
 'IFCB2009_17.xls',
 'IFCB2009_170.xls',
 'IFCB2009_171.xls',
 'IFCB2009_18.xls',
 'IFCB2009_19.xls',
 'IFCB2009_20.xls',
 'IFCB2009_21.xls',
 'IFCB2009_22.xls',
 'IFCB2009_23.xls',
 'IFCB2009_24.xls',
 'IFCB2009_25.xls',
 'IFCB2009_26.xls',
 'IFCB2009_27.xls',
 'IFCB2009_28.xls',
 'IFCB2009_29.xls',
 'IFCB2009_30.xls',
 'IFCB2009_31.xls',
 'IFCB2009_32.xls',
 'IFCB2009_33.xls',
 'IFCB2009_34.xls',
 'IFCB2009_35.xls',
 'IFCB2009_36.xls',
 'IFCB2009_37.xls',
 'IFCB2009_38.xls',
 'IFCB2009_39.xls',
 'IFCB2009_40.xls',
 'IFCB2009_41.xls',
 'IFCB2009_42.xls',
 'IFCB2009_43.xls',
 'IFCB2009_44.xls',
 'IFCB2009_45.xls',
 'IFCB2009_46.xls',
 'IFCB2009_47.xls',
 'IFCB2009_48.xls',
 'IFCB2009_49.xls',
 'IFCB2009_50.xls',
 'IFCB2009_51.xls',
 'IFCB2009_52.xls',
 'IFCB2009_53.xls',
 'IFCB2009_54.xls',
 'IFCB2009_55.xls',
 'IFCB2009_56.xls',
 'IFCB2009_57.xls',
 'IFCB2009_58.xls',
 'IFCB2009_59.xls',
 'IFCB2009_60.xls',
 'IFCB2009_61.xls',
 'IFCB2009_62.xls',
 'IFCB2009_63.xls',
 'IFCB2009_64.xls',
 'IFCB2009_65.xls',
 'IFCB2009_66.xls',
 'IFCB2009_67.xls',
 'IFCB2009_68.xls',
 'IFCB2009_69.xls',
 'IFCB2009_70.xls',
 'IFCB2009_71.xls',
 'IFCB2009_72.xls',
 'IFCB2009_73.xls',
 'IFCB2009_74.xls',
 'IFCB2009_75.xls',
 'IFCB2009_76.xls',
 'IFCB2009_77.xls',
 'IFCB2009_78.xls',
 'IFCB2009_79.xls',
 'IFCB2009_80.xls',
 'IFCB2009_81.xls',
 'IFCB2009_82.xls',
 'IFCB2009_83.xls',
 'IFCB2009_84.xls',
 'IFCB2009_85.xls',
 'IFCB2009_86.xls',
 'IFCB2009_87.xls',
 'IFCB2009_88.xls',
 'IFCB2009_89.xls',
 'IFCB2009_90.xls',
 'IFCB2009_91.xls',
 'IFCB2009_92.xls',
 'IFCB2009_93.xls',
 'IFCB2009_94.xls',
 'IFCB2009_95.xls',
 'IFCB2009_96.xls',
 'IFCB2009_97.xls',
 'IFCB2009_98.xls',
 'IFCB2009_99.xls']

In [38]:
df = pd.DataFrame()

In [39]:
for f in files:
    data = pd.read_excel(path+'\\'+f, header=None, skiprows=[0])
    data.columns = ['BANK','IFSC','MICR_CODE','BRANCH','ADDRESS','CONTACT','CITY','DISTRICT','STATE']
    print(f,data.columns)
    df = df.append(data)

IFCB2009_01.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_02.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_03.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_04.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_05.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_06.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_07.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_08.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_09.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_10.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_100.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_101.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_102.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_104.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_105.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_106.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_107.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_108.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_109.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_11.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_111.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_112.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_113.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_114.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_116.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_117.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_118.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_119.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_12.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_120.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_121.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_122.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_123.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_124.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_125.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_126.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_127.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_128.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_129.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_13.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_130.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_131.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_132.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_133.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_135.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_136.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_137.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_138.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_139.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_14.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_140.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_141.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_142.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_143.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_144.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_145.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_146.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_147.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_148.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_149.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_15.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')

IFCB2009_150.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_151.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_152.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_153.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_154.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_155.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_156.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_157.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_158.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_159.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_16.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_160.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_161.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_162.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_163.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_164.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_165.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_166.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_17.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_170.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_171.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_18.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_19.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_20.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_21.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_22.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_23.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_24.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_25.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_26.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_27.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_28.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_29.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_30.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_31.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_32.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_33.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_34.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_35.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_36.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_37.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_38.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_39.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_40.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_41.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_42.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_43.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_44.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_45.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_46.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_47.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_48.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_49.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_50.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_51.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_52.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_53.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_54.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')

IFCB2009_55.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_56.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_57.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_58.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_59.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_60.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_61.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_62.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_63.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_64.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_65.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_66.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_67.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_68.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_69.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_70.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_71.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_72.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_73.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_74.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_75.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_76.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_77.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_78.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_79.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_80.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_81.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_82.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_83.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_84.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_85.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_86.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_87.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_88.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_89.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_90.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_91.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_92.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_93.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_94.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_95.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_96.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_97.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_98.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')
IFCB2009_99.xls Index(['BANK', 'IFSC', 'MICR_CODE', 'BRANCH', 'ADDRESS', 'CONTACT', 'CITY',
       'DISTRICT', 'STATE'],
      dtype='object')

In [40]:
df

,BANK,IFSC,MICR_CODE,BRANCH,ADDRESS,CONTACT,CITY,DISTRICT,STATE
0,ABU DHABI COMMERCIAL BANK,ADCB0000001,4.00269e+08,RTGS-HO,"75, REHMAT MANZIL, V. N. ROAD, CURCHGATE, MUMB...",39534100,MUMBAI,MUMBAI CITY,MAHARASHTRA
1,ABU DHABI COMMERCIAL BANK,ADCB0000002,5.60269e+08,BANGALORE,"CITI CENTRE, 28, CHURCH STREET, OFF M. G. ROAD...",25582000,BANGALORE,BANGALORE URBAN,KARNATAKA
0,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065001,4.00065e+08,RTGS-HO,"ABHYUDAYA BANK BLDG., B.NO.71, NEHRU NAGAR, KU...",25260173,MUMBAI,GREATER MUMBAI,MAHARASHTRA
1,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065002,4.00065e+08,ABHYUDAYA NAGAR,"ABHYUDAYA EDUCATION SOCIETY, OPP. BLDG. NO. 18...",24702643,MUMBAI,GREATER MUMBAI,MAHARASHTRA
2,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065003,4.00065e+08,BAIL BAZAR,"KMSPM'S SCHOOL, WADIA ESTATE, BAIL BAZAR-KURLA...",25032202,MUMBAI,GREATER MUMBAI,MAHARASHTRA
3,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065004,4.00065e+08,BHANDUP,"CHETNA APARTMENTS, J.M.ROAD, BHANDUP, MUMBAI-4...",25963157,MUMBAI,GREATER MUMBAI,MAHARASHTRA
4,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065005,4.00065e+08,DARUKHANA,"POTIA IND.ESTATE, REAY ROAD (E), DARUKHANA, MU...",23778164,MUMBAI,GREATER MUMBAI,MAHARASHTRA
5,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065006,4.00065e+08,FORT,"ABHYUDAYA BANK BLDG., 251, PERIN NARIMAN STREE...",22614468,MUMBAI,GREATER MUMBAI,MAHARASHTRA
6,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065007,4.00065e+08,GHATKOPAR,"UNIT NO 2 & 3, SILVER HARMONY BLDG,NEW MANIKLA...",25116673,MUMBAI,GREATER MUMBAI,MAHARASHTRA
7,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065008,4.00065e+08,KANJUR,"BHANDARI CO-OP. HSG. SOCIETY, KANJUR VILLAGE, ...",25783519,MUMBAI,GREATER MUMBAI,MAHARASHTRA
8,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065009,4.00065e+08,NEHRU NAGAR,"ABHYUDAYA BANK BLDG., B.NO.71, NEHRU NAGAR, KU...",25222386,MUMBAI,GREATER MUMBAI,MAHARASHTRA
9,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065010,4.00065e+08,PAREL,"SHRAMA SAFALYA, 63 G.D.AMBEKAR MARG, PAREL VIL...",24137707,MUMBAI,GREATER MUMBAI,MAHARASHTRA
10,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065011,4.00065e+08,SEWRI,"NAVNIDHI INDUSTRIAL ESTATE, ACHARYA DONDHE MAR...",24136008,MUMBAI,GREATER MUMBAI,MAHARASHTRA
11,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065012,4.00065e+08,WADALA,"B.P.T.MARKET BLDG., NADKARNI PARK, WADALA (EAS...",24184512,MUMBAI,GREATER MUMBAI,MAHARASHTRA
12,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065013,4.00065e+08,WORLI,"LANDMARK,NEXT TO MAHINDRA TOWERS, PLOT NO.1, J...",24921104,MUMBAI,GREATER MUMBAI,MAHARASHTRA
13,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065014,4.00065e+08,MUMBRA,"RIZVI APARTMENTS, OPP. RAILWAY STATION, MUMBRA...",25462172,MUMBAI,GREATER MUMBAI,MAHARASHTRA
14,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065015,4.00065e+08,TURBHE,"A.P.M.C.MARKET, ADMINISTRATIVE BLDG, TURBHE, N...",27888044,MUMBAI,GREATER MUMBAI,MAHARASHTRA
15,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065016,4.00065e+08,VASHI,"ABHYUDAYA BANK BLDG., SECTOR 17, VASHI, NAVI M...",27892458,MUMBAI,GREATER MUMBAI,MAHARASHTRA
16,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065017,4.00065e+08,MOBILE BANK,"ABHYUDAYA BANK BLDG., SECTOR 17, VASHI, NAVI M...",27892444,MUMBAI,GREATER MUMBAI,MAHARASHTRA
17,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065018,4.00065e+08,NEW PANVEL,"ABHYUDAYA BANK BLDG., SECTOR 17, NEW PANVEL-41...",27453585,MUMBAI,GREATER MUMBAI,MAHARASHTRA
18,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065019,4.00065e+08,KALAMBOLI,"BLDG F-4, SHOP NO 17-20, SECTOR 3 EB, KALAMBOL...",27420148,MUMBAI,GREATER MUMBAI,MAHARASHTRA
19,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065020,4.00065e+08,DHARAVI,"WESTERN INDIA TANNERIES, SION DHARAVI ROAD, MU...",24077126,MUMBAI,GREATER MUMBAI,MAHARASHTRA
20,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065021,4.00065e+08,MALAD EAST,"148 ELLORA SHOPPING CENTRE, DAFTARY ROAD, MALA...",28800272,MUMBAI,GREATER MUMBAI,MAHARASHTRA
21,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065022,4.00065e+08,CBD BELAPUR,"SECTOR-3, CHANAKYA SHOPPING CENTRE, BELAPUR (C...",27572179,MUMBAI,GREATER MUMBAI,MAHARASHTRA
22,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065023,4.00065e+08,BHIWANDI,"BLDG F-1,GOPAL NAGAR,BHIWANDI-KALYAN ROAD, BHI...",251852,MUMBAI,GREATER MUMBAI,MAHARASHTRA
23,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065024,4.00065e+08,BORIVALI,"RATNADEEP APARTMENTS, CARTER ROAD NO.1, BORIVL...",28636529,MUMBAI,GREATER MUMBAI,MAHARASHTRA
24,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065025,4.00065e+08,HILL ROAD,"HILL-N-DALE, HILL ROAD, NR.BANDRA POLICE STATI...",26402597,MUMBAI,GREATER MUMBAI,MAHARASHTRA
25,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065026,4.00065e+08,KHER NAGAR,"JANATA EDUCATION SOC. PREMISES, KHER NAGAR, BA...",26473470,MUMBAI,GREATER MUMBAI,MAHARASHTRA
26,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065027,4.00065e+08,KANDIVLI-EAST,"GUNDECHA INDL.COMPLEX, AKURLI RD, KANDIVLI (E)...",28851962,MUMBAI,GREATER MUMBAI,MAHARASHTRA
27,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065028,4.00065e+08,SHERLY RAJAN,"KHAIR HOUSE, SHERLY RAJAN RD, BANDRA (WEST), M...",26047905,MUMBAI,GREATER MUMBAI,MAHARASHTRA
...,...,...,...,...,...,...,...,...,...
1749,VIJAYA BANK,VIJB0009630,NaN,"CURRENCY CHEST, KURNOOL","CURRENCY CHEST, KURNOOL,40/301-1, OPP. BALAJI ...",223431,"KURNOOL,ANDHRA PRADESH","KURNOOL,ANDHRA PRADESH",ANDHRA PRADESH
1750,VIJAYA BANK,VIJB0009701,WAITING,STAFF TRAINING COLLEGE BAN,NO 135TH CROSS 560009,0,BANGALORE,BANGALORE,KARNATAKA
1751,VIJAYA BANK,VIJB0009707,302029015,STC JAIPUR,"A 9 10,3RD FLOOR,JANTA STORE,BAPU NAGARJAIPUR ...",0,JAIPUR,JAIPUR,RAJASTHAN
1752,VIJAYA BANK,VIJB0009801,NaN,RACPC-AHMEDABAD,"RACPC-AHMEDABAD,KAMDHENU COMPLEX,,PANJARAPOLE,...",0,AHEMDABAD,AHEMDABAD,GUJARAT
1753,VIJAYA BANK,VIJB0009802,NaN,RACPC-BANGALORE,"RACPC-BANGALORE,SHRUTHA COMPLEX,19,PRIME ROSE ...",0,BANGALORE,BANGALORE,KARNATAKA
1754,VIJAYA BANK,VIJB0009803,NaN,RACPC-CHENNAI,"RACPC-CHENNAI,182,ANKUR MANOR,P H ROAD,KILPAUK...",0,CHENNAI,CHENNAI,TAMIL NADU
1755,VIJAYA BANK,VIJB0009804,NaN,RACPC-DELHI,"RACPC-DELHI,REGIONAL OFFICE,17, BARKHAMBA ROAD...",23352816,DELHI,DELHI,DELHI
1756,VIJAYA BANK,VIJB0009805,NaN,RACPC-HYDERABAD,"RACPC-HYDERABAD,105,IST FLOOR,BABUKHAN ESTATE,...",0,HYDERABAD,HYDERABAD,ANDHRA PRADESH
1757,VIJAYA BANK,VIJB0009806,NaN,RACPC-KOLKATA,"RACPC-KOLKATA,P-17A TEMPLE TOWERS,ASHUTOSH CHO...",0,KOLKATA,KOLKATA,WEST BENGAL
1758,VIJAYA BANK,VIJB0009808,NaN,RACPC-MANGALORE,"RACPC-MANGALORE,VIJAYA TOWER,2ND FLOOR,LHH ROA...",2442903,MANGALORE,MANGALORE,KARNATAKA
1759,VIJAYA BANK,VIJB0009809,NaN,RACPC-MUMBAI,"RACPC-MUMBAI,1/B,ALKA CHAMBERS,S V ROAD,ANDHER...",26240502,MUMBAI,MUMBAI,MAHARASHTRA
1760,VIJAYA BANK,VIJB0009810,NaN,RACPC-MYSORE,"RACPC-MYSORE,#1, SHALIVAHANA ROAD,NAZARBAD,MYS...",2424002,MYSORE,MYSORE,KARNATAKA
1761,VIJAYA BANK,VIJB0009811,NaN,RACPC-PUNE,"RACPC-PUNE,NO.1206/A-32,SHIROLE ROAD,OPP SAMBH...",30203379,PUNE,PUNE,MAHARASHTRA
1762,VIJAYA BANK,VIJB0009812,NaN,RACPC-CHANDIGARH,"RACPC-CHANDIGARH,L I C BUILDING,SECTOR 17 B,,C...",0,CHANDIGARH,CHANDIGARH,CHANDIGARH
1763,VIJAYA BANK,VIJB0009813,NaN,RACPC-HUBLI,"RACPC-HUBLI,NO-84,RAMSON COMPLEX,HOSUR,VIDYANA...",2374855,HUBLI,HUBLI,KARNATAKA
1764,VIJAYA BANK,VIJB0009814,NaN,RACPC-COIMBATORE,"RACPC-COIMBATORE,42/7-10,AHUJA TOWERS,T V SWAM...",0,COIMBATORE,COIMBATORE,TAMIL NADU
1765,VIJAYA BANK,VIJB0009815,NaN,RACPC-TIRUCHIRAPALLI,"RACPC-TIRUCHIRAPALLI,74-A,SALAI ROAD,,,TIRUCHI...",0,"TIRUCHIRAPALLI,TAMILNADU","TIRUCHIRAPALLI,TAMILNADU",TAMIL NADU
1766,VIJAYA BANK,VIJB0009816,NaN,"RACPC, KOCHI","RACPC, KOCHI,RACPC, KOCHI,,KOCHI,KERALA",0,KOCHI,KOCHI,KERALA
1767,VIJAYA BANK,VIJB0009852,NaN,"MSME CELL, BANGALORE (N)","MSME CELL, BANGALORE (N),SHRUTHA COMPLEX,19, P...",0,BANGALORE,BANGALORE,KARNATAKA
1768,VIJAYA BANK,VIJB0009853,111029000,MSME-RACPC CHENNAI,"MSME-RACPC CHENNAI,NO-123,DUGAR TOWERS,MARSHAL...",0,CHENNAI,CHENNAI,TAMIL NADU
1769,VIJAYA BANK,VIJB0009854,NaN,MSME - CPC,"MSME - CPC,MSME-CPC,REGIONAL OFFICE,3RD FLOOR,...",0,DELHI,DELHI,DELHI
1770,VIJAYA BANK,VIJB0009855,NaN,MSME BR PROCESSING CENTRE-HYD,"MSME BR PROCESSING CENTRE-HYD,III FLOOR,BABUKH...",0,HYDERABAD,HYDERABAD,ANDHRA PRADESH
1771,VIJAYA BANK,VIJB0009856,NaN,MSME- R A C,"MSME- R A C,NO 10, PADMA NAGAR, LINK ROAD,MALA...",0,MUMBAI,MUMBAI,MAHARASHTRA
1772,VIJAYA BANK,VIJB0009857,NaN,MSME CELL PUNE,"MSME CELL PUNE,VINAYAK NIWAS,1206/A SHIROLE RO...",0,PUNE,PUNE,MAHARASHTRA
1773,VIJAYA BANK,VIJB0009859,NaN,MSME RAIPUR,"MSME RAIPUR,MAHADEV GHAT ROAD,SURENDER NAGAR,R...",2241939,"RAIPUR,CHATTISGARH","RAIPUR,CHATTISGARH",MAHARASHTRA
1774,VIJAYA BANK,VIJB0009860,NaN,"MSME, COIMBATORE","MSME, COIMBATORE,3RD FLR,RAJA PLAZA,1112 AVINA...",0,COIMBATORE,COIMBATORE,TAMIL NADU
1775,VIJAYA BANK,VIJB0009862,NaN,VIJAYA KRISHI VIKAS KENDRA,"VIJAYA KRISHI VIKAS KENDRA,VIJAYAVIKAS KENDRA ...",0,"SANGLI,MAHARASTRA","SANGLI,MAHARASTRA",MAHARASHTRA
1776,VIJAYA BANK,VIJB0009863,701029016,KOLKATA MSME CELL,"KOLKATA MSME CELL,TRIMURTHI APARTMENTS,5TH FLO...",0,KOLKATA,KOLKATA,WEST BENGAL
1777,VIJAYA BANK,VIJB0LMB001,NaN,LOKAPAVANI MAHILA,"NIYAMITHA,VINOBA RD,SUBHASH NAGAR,MANDYA 571401",0,MANDYA,MANDYA,KARNATAKA
1778,VIJAYA BANK,VIJB0SSB001,NaN,SHIMSHA SAHAKARA BANK NIYAMITHA,"SHIMSHA SAHAKARA BANK NIYAMITHA,BESIDE TALUK P...",0,MADDUR,MANDYA,KARNATAKA

In [41]:
df.to_csv(path+'\\'+"All_Bank_IFSC_CODE.csv", index=False)

In [30]:
import json
test = open("training.json"))
ls = []
for i in test.readlines():
    ls.append(i)

In [87]:
pd.DataFrame([json.loads(ls[0])])

   Chemistry  English  Mathematics  PhysicalEducation  Physics  serial
0          7        4            6                  3        8  195490

In [93]:
ref = {'serial':0,'Accountancy':0,'Biology':0,'BusinessStudies':0,'Chemistry':0,'ComputerScience':0,'Economics':0,'English':0,'PhysicalEducation':0,'Physics':0}

In [94]:
for k,v in json.loads(ls[0]).items():
    ref[k] = v

In [113]:
del ref['serial']

In [104]:
import numpy as np

In [114]:
np.reshape(list(ref.values()), (-1,1))

array([[0],
       [0],
       [0],
       [7],
       [0],
       [0],
       [4],
       [3],
       [8],
       [6]])

In [121]:
type((pd.DataFrame([ref]).iloc[:,1:].values))

numpy.ndarray

In [78]:
lsv = []

In [79]:
for j in range(len(ls)):
    lsv.append(json.loads(ls[j]))

In [83]:
len(pd.DataFrame(lsv).fillna(value=0))

79465

In [71]:
df = pd.DataFrame()

In [72]:
for j in range(len(ls)):
    d = pd.DataFrame([json.loads(ls[j])])
    df = df.append(d)

C:\Users\5029874\AppData\Local\Continuum\anaconda3\envs\trainingenv\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [76]:
df = df.fillna(value=0)

In [3]:
import pandas as pd

In [84]:
df.columns

Index(['Accountancy', 'Biology', 'BusinessStudies', 'Chemistry',
       'ComputerScience', 'Economics', 'English', 'Mathematics',
       'PhysicalEducation', 'Physics', 'serial'],
      dtype='object')